# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: imprun

builds:
  - id: imprun
    main: ./cmd/imprun
    binary: imprun
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/imprun/cli/internal/controlcli.Version={{.Version}}

archives:
  - ids:
      - imprun
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
          - binary
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - LICENSE
      - README.md

checksum:
  name_template: checksums.txt
  extra_files:
    - glob: ./install.sh
    - glob: ./install.ps1

release:
  prerelease: auto
  extra_files:
    - glob: ./install.sh
    - glob: ./install.ps1

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
